### ISSUE TITLE
External source links not working

### ISSUE THREAD

**Issue by asturur** [HiDeoo/starlight-typedoc#34] opened 2024-03-24 02:18 UTC
### Describe the bug

I m trying to get external source links from my documentation to github, and i specified that using the typeDoc options:

```
      starlightTypeDoc({
        entryPoints: ['./node_modules/fabric/fabric.ts'],
        tsconfig: './node_modules/fabric/typedoc.config.json',
        typeDoc: {
          plugin: ['typedoc-plugin-no-inherit'],
          readme: 'none',
          gitRemote: 'https://github.com/fabricjs/fabric.js/blob',
          gitRevision: 'v6.0.0-beta20',
          entryFileName: 'index.md',
          includeVersion: true,
          sourceLinkExternal: true,
          sourceLinkTemplate: 'https://github.com/fabricjs/fabric.js/blob/{gitRevision}/{path}#L{line}',
        },
      }),
```

The links i get in my documentation is always relative:

<img width="389" alt="image" src="https://github.com/HiDeoo/starlight-typedoc/assets/1194048/7530973b-a9d5-4669-849c-e455643dea2f">

While i would like to have a link to the repo and file of that part of source code.

### To Reproduce

-

### Expected behavior

I see a link to github as specified in the template

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment] 2024-03-24 08:49
Thanks for the report.

I am having a bit of trouble reproducing this issue. Would you be able to share some sort of mininal example that reproduces the issue?

I tested using the following steps:

1. Clone this repository
2. Run `pnpm i`
3. Go in the `example/` folder
4. Edit the plugin configuration in `astro.config.ts` to include the following:

   ```ts
   gitRevision: 'v6.0.0-beta20',
   sourceLinkTemplate: 'https://github.com/fabricjs/fabric.js/blob/{gitRevision}/{path}#L{line}',
   ```

5. Run `pnpm dev` in the `example/` folder
6. Visit a page like [`http://localhost:4321/api/functions/dothingb/`](http://localhost:4321/api/functions/dothingb/)

The source link at the bottom has the following URL `https://github.com/fabricjs/fabric.js/blob/v6.0.0-beta20/fixtures/basics/src/functions.ts#L12` which seems to be correct to me.

**Comment by asturur** [comment] 2024-03-24 09:04
i can try to make a small repo with the reproduction tomorrow.
My full case is here:
https://github.com/fabricjs/fabricjs.github.io

And i understand maybe pulling down that and try to build is not the way to report an issue.

I ll try to replicate it in small.

**Comment by HiDeoo** [comment] 2024-03-24 09:13
> I ll try to replicate it in small.

Thanks a lot. Links related code can be invoked a lot of times so large projects can be very difficult to debug so that would be very helpful (if for some reason you can't reduce the code to a small example tho, let me know and we will try on the full code).

**Comment by asturur** [comment] 2024-03-27 07:29
https://github.com/asturur/starlight-typedoc/pull/1/files#

I tried to make it work, i can't.
I clone the repo, swapped the config and that single file the typedocs were good

then i tried to swap the single ts file with fabricJS and that is where the issue started, i first had to update to TS 5.3.3 and typedoc 0.25.12 and once i managed to compile the docs i get no ouput files anywhere.

**Comment by asturur** [comment] 2024-03-27 07:51
Ok my link now works, it compiles it create the files, and indeed there are no links.
So is either something with:
- fabricJS ( hopefully not )
- typedoc 0.25.12

**Comment by asturur** [comment] 2024-03-27 07:52
I scanned the changelog of typedoc but i couldn't find bugfixes or changes that rang a bell to me.
One of them was for opening links to a new tab, all the rest seem unrelated

**Comment by asturur** [comment] 2024-04-04 16:45
@HiDeoo my reproduction does give you any idea of what could be going wrong?

**Comment by HiDeoo** [comment] 2024-04-05 16:29
Finally got time to get back to this.

I tested this use case with only TypeDoc (no markdown plugin or Starlight involved) and it looks like this is an limitation of TypeDoc itself.

For example, using this basic configuration:

```json
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": ["index.ts"],
  "sourceLinkExternal": true,
  "gitRevision": "v6.0.0-beta20",
  "sourceLinkTemplate": "https://github.com/fabricjs/fabric.js/blob/{gitRevision}/{path}#L{line}"
}
```

With a very basic file exporting 1 function, I get a link in the generated documentation and it properly links to `https://github.com/fabricjs/fabric.js/blob/v6.0.0-beta20/index.ts#L1` as expected from the configuration.

<img width="209" alt="SCR-20240405-qbdw" src="https://github.com/HiDeoo/starlight-typedoc/assets/494699/89ccd818-fcee-452e-9164-076b61b66bd9">

If I update the configuration to:

```diff
{
  "$schema": "https://typedoc.org/schema.json",
-  "entryPoints": ["index.ts"],
+  "entryPoints": ["node_modules/test-typedoc/index.ts"],
  "sourceLinkExternal": true,
  "gitRevision": "v6.0.0-beta20",
  "sourceLinkTemplate": "https://github.com/fabricjs/fabric.js/blob/{gitRevision}/{path}#L{line}"
}
```

With the exact same code, I do not get a link in the generated documentation.

<img width="207" alt="SCR-20240405-qbhw" src="https://github.com/HiDeoo/starlight-typedoc/assets/494699/f81f4dce-4abe-46a1-813c-4af302817f15">

My guess would be this [limitation](https://github.com/TypeStrong/typedoc/issues/1495#issuecomment-774130774):

> 1. The source code isn't in a git repo with an origin that TypeDoc understands
> 2. The files aren't tracked by the git repo.

Having the code in `node_modules` and having it not tracked by the git repository would explain why links are not generated.

Considering this, I am going to close this issue as there is not much we can do on this side.

**Closed by HiDeoo** 2024-04-05 16:29 UTC
Labels: needs-reproduction

**Comment by asturur** [comment] 2024-04-07 07:51
Thank for looking into this.
So the first thing i could try to do is to add the library in the website repo and just not commit it, another option could be having a sibling folder with the library  repository

**Comment by asturur** [comment] 2024-06-25 22:43
Just to say that i came back to this, added the library with git submodule and everything works fine
